CXXFLAGS += -DMCSL_NAUTILUS -DTPAL_NAUTILUS -DTPALRTS_STATS -Iinclude/rt/mcsl -Iinclude/rt/tpal -Wno-return-type -Wno-write-strings #-DNDEBUG

obj-y += benchmark0.o benchmark.o \
	incr_array_manual.o \
	plus_reduce_array_manual.o \
	floyd_warshall_manual.o \
	mandelbrot_manual.o \
	kmeans_manual.o \
	spmv_manual.o \
	knapsack_manual.o \
	mergesort_manual.o

