CPPFLAGS += -DNDEBUG -DMCSL_NAUTILUS -DTPAL_NAUTILUS -DTPALRTS_STATS -DTPALRTS_USE_INTERRUPT_FLAGS -Iinclude/rt/mcsl -Iinclude/rt/tpal

obj-y += bench.o tpal.o incr_array_manual.o
#plus_reduce_array_manual.o spmv_manual.o
